name: Test OpenFOAM version

on:
  push:
    branches: [ main ]

jobs:
  test-openfoam:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup OpenFOAM
        uses: gerlero/setup-openfoam@v1
        with:
          openfoam-version: '2506'   # ajuste para a versão que você quer testar

      - name: Print OpenFOAM env and check version
        run: |
          echo "=== ENV OpenFOAM relevantes ==="
          echo "WM_PROJECT = ${WM_PROJECT:-not-set}"
          echo "WM_PROJECT_VERSION = ${WM_PROJECT_VERSION:-not-set}"
          echo "FOAM_PROJECT = ${FOAM_PROJECT:-not-set}"
          echo "FOAM_SRC = ${FOAM_SRC:-not-set}"
          echo "FOAM_ETC = ${FOAM_ETC:-not-set}"
          echo "FOAM_RUN = ${FOAM_RUN:-not-set}"
          echo

          # carrega bashrc do OpenFOAM se estiver disponível
          if [ -n "$FOAM_ETC" ] && [ -f "$FOAM_ETC/bashrc" ]; then
            echo "Sourcing $FOAM_ETC/bashrc"
            # não falhar se source der problema
            source "$FOAM_ETC/bashrc" || true
          fi

          echo
          echo "=== Tentando comandos de verificação ==="
          if command -v foamVersion >/dev/null 2>&1; then
            echo "Comando foamVersion encontrado — saída:"
            foamVersion || true
          elif command -v foamInstallationTest >/dev/null 2>&1; then
            echo "Comando foamInstallationTest encontrado — saída:"
            foamInstallationTest || true
          else
            echo "Nenhum comando de verificação padrão (foamVersion/foamInstallationTest) disponível."
            echo "Listando diretórios em \$FOAM_SRC para confirmar instalação:"
            if [ -n "$FOAM_SRC" ]; then
              ls -la "$FOAM_SRC" | sed -n '1,200p' || true
            fi
          fi

          echo
          echo "=== Fim do teste de versão ==="
