name: CI
on:
  push:
    branches: [ main ]   # 

jobs:
  build:
    runs-on: ubuntu-latest   # Runner Linux Ubuntu
    steps:
      - uses: actions/checkout@v4        # Clona o código:contentReference[oaicite:10]{index=10}
      - uses: gerlero/setup-openfoam@v1  # Prepara OpenFOAM (versão 2506):contentReference[oaicite:11]{index=11}
        with:
          openfoam-version: 2506
      - name: Compilar o solver
        run: |
          # Caso o solver esteja em subdiretório, use cd. Exemplo:
          # cd applications/solvers/darcyBrinkmanFoam
          wmake  # Compila o solver (encerra com erro se falhar)
