name: Test OpenFOAM build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup OpenFOAM
        uses: gerlero/setup-openfoam@v1
        with:
          openfoam-version: 2506

      - name: Debug: imprimir variáveis do OpenFOAM e listar lnInclude
        run: |
          echo "=== ENV relevantes ==="
          echo "FOAM_SRC = $FOAM_SRC"
          echo "FOAM_ETC = $FOAM_ETC"
          echo "WM_PROJECT = ${WM_PROJECT:-OpenFOAM} (${WM_PROJECT_VERSION:-unknown})"
          echo
          if [ -d "$FOAM_SRC/OpenFOAM/lnInclude" ]; then
            echo "### lnInclude existe:"
            ls -la "$FOAM_SRC/OpenFOAM/lnInclude" | sed -n '1,200p'
          else
            echo ">>> $FOAM_SRC/OpenFOAM/lnInclude NÃO existe"
          fi
          echo
          echo "### Procurando por Scalar.H / scalar.h"
          find "$FOAM_SRC" -type f -name 'Scalar.H' -print || true
          find "$FOAM_SRC" -type f -iname 'scalar.h' -print || true
          echo
          echo "=== Primeiro trecho do solver (se presente) ==="
          if [ -f "./darcyBrinkmanFoam.C" ]; then
            sed -n '1,80p' darcyBrinkmanFoam.C || true
          else
            echo "Arquivo darcyBrinkmanFoam.C não encontrado no workspace root — verifique o caminho"
            ls -la
          fi

      - name: (Opcional) Mostrar Make/options e Make/files
        run: |
          if [ -d "./Make" ]; then
            echo "=== Make dir contents ==="
            ls -la Make || true
            echo "=== Make/options ==="
            sed -n "1,200p" Make/options || true
            echo "=== Make/files ==="
            sed -n "1,200p" Make/files || true
          else
            echo "Não há diretório Make/ no repo (ou está em outro local)."
          fi

      - name: Compilar (wmake) — com ambiente OpenFOAM carregado
        run: |
          set -o pipefail
          if [ -n "$FOAM_ETC" ]; then
            source "$FOAM_ETC/bashrc"
          fi
          # Se o solver estiver em subdiretório, descomente e ajuste:
          # cd applications/solvers/darcyBrinkmanFoam
          echo "Current dir: $(pwd)"
          ls -la
          wmake
